name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2.5.2
    
    - name: Make Report
      run: |
        go install github.com/lemon-mint/golang-ci-tools@latest
        echo "REPORT=$(golang-ci-tools)" >> $GITHUB_ENV
    - name: commit-comment
      uses: peter-evans/commit-comment@v1
      with:
        body: ${{ env.REPORT }}

